### ISSUE TITLE
EC2-only rake task

### ISSUE THREAD

**Issue by rgindes** [cloudpassage/cloudpassage-chef-cookbook#16]
Hi guys -- could you add a task to the Rakefile which would do style, Chefspec and ec2 testing only? We like to be able to have our CI tools run a task like that so we don't have to equip our CI agent/slave servers with VirtualBox.

I can submit a PR -- it's just one line for the Rakefile; please let me know if you have any questions.

**Comment by ashmastaflash** [comment]
Added `rake cloud` to provide style, spec, and EC2 integration testing.
