### ISSUE TITLE
Service resource uses systemd resource for amazon linux

### ISSUE THREAD

**Issue by lindsay-apitalent** [cloudpassage/cloudpassage-chef-cookbook#34]
agent.rb line 77

For amazon linux the platform is reported as rhel and the version is YYYY.MM which is greater than 7 so systemd is incorrectly selected.

**Comment by cloudoperator** [comment]
Hi do we have a response to this issue. We are really trying to get this going. Currently this is the output of the logs. ================================================================================

# Error executing action `restart` on resource 'service[CloudPassage Halo Agent for Linux]'

## Mixlib::ShellOut::ShellCommandFailed

Expected process to exit with [0], but received '1'
---- Begin output of false restart cphalod ----
STDOUT: 
STDERR: 
---- End output of false restart cphalod ----
Ran false restart cphalod returned 1

## Cookbook Trace:

/var/chef/runs/b838e77f-0c0c-4a41-9aca-56fe946ad6c9/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:123:in `compile_and_converge_action'

## Resource Declaration:

# In /var/chef/runs/b838e77f-0c0c-4a41-9aca-56fe946ad6c9/local-mode-cache/cache/cookbooks/cloudpassage/resources/agent.rb

77:     service 'CloudPassage Halo Agent for Linux' do
78:       service_name 'cphalod'
79:       # Force systemd for RHEL 7+.
80:       if node['platform_family'] == 'rhel' && node['platform_version'].to_f >= 7
81:         provider Chef::Provider::Service::Systemd
82:       end
83:       supports [:start, :stop, :restart]

## Compiled Resource:

# Declared in /var/chef/runs/b838e77f-0c0c-4a41-9aca-56fe946ad6c9/local-mode-cache/cache/cookbooks/cloudpassage/resources/agent.rb:77:in `block in class_from_file'

service("CloudPassage Halo Agent for Linux") do
provider Chef::Provider::Service::Systemd
action [:restart]
supports {:restart=>true, :reload=>nil, :status=>nil, :start=>true, :stop=>true}
retries 0
retry_delay 2
default_guard_interpreter :default
service_name "cphalod"
pattern "CloudPassage Halo Agent for Linux"
declared_type :service
cookbook_name "cloudpassage"
end

[2016-03-02T23:25:07+00:00] INFO: Running queued delayed notifications before re-raising exception

**Comment by ashmastaflash** [comment]
Hi there, sorry to keep you waiting.
I'll get this taken care of ASAP.

**Comment by cloudoperator** [comment]
Thanks!

**Comment by ashmastaflash** [comment]
Hey y'all,
  What versions of Amazon Linux are you trying with?  I want to roll the specific ones you're using into test-kitchen.

Thanks for your patience!

**Comment by awilson-cloudpassage** [comment]
I'm putting Amazon Linux 2015.09 into the kitchen-ec2 config, being more specific with service management overrides in the LWRP.  Hoping to push a new minor version later today.

**Comment by ashmastaflash** [comment]
Fixed in v2.5.0.  New cookbook uploaded to supermarket, source available in master branch.

Closing.
