### ISSUE TITLE
store.db exists - configurator never runs

### ISSUE THREAD

**Issue by stormlrd** [cloudpassage/cloudpassage-chef-cookbook#37]
Hi,

The recipe needs a fix.

Agent.rb has:
  # We don't run the configurator if the store.db file already exists
      not_if { ::File.exist?('/opt/cloudpassage/data/store.db') }

This should be removed as the default install of CloudPassage installs a store.db ?

Well I'm assuming it does.

I have run your cookbook and I get an error.. but if I login to my kitchen and run the configurator again it saves the config correctly and then agent starts.. 

so I can only presume this Not_If clause is breaking this cookbook! :(

I am on CentOS.

I could really do with a fix.. 

```
   Running handlers:
   [2016-04-26T09:17:33+00:00] ERROR: Running exception handlers
   Running handlers complete
   [2016-04-26T09:17:33+00:00] ERROR: Exception handlers complete
   Chef Client failed. 51 resources updated in 03 minutes 55 seconds
   [2016-04-26T09:17:33+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
   [2016-04-26T09:17:33+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
   [2016-04-26T09:17:33+00:00] ERROR: cloudpassage_agent[halo] (cloudpassage::default line 27) had an error: Mixlib::ShellOut::ShellCommandFailed: service[CloudPassage Halo Agent for Linux] (/tmp/kitchen/cache/cookbooks/cloudpassage/resources/agent.rb line 77) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
   ---- Begin output of /bin/systemctl --system restart cphalod ----
   STDOUT: 
   STDERR: Job for cphalod.service failed because the control process exited with error code. See "systemctl status cphalod.service" and "journalctl -xe" for details.
   ---- End output of /bin/systemctl --system restart cphalod ----
   Ran /bin/systemctl --system restart cphalod returned 1
   [2016-04-26T09:17:33+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

> > > > > > Converge failed on instance <default-centos-72>.
> > > > > > Please see .kitchen/logs/default-centos-72.log for more details
> > > > > > ------Exception-------
> > > > > > Class: Kitchen::ActionFailed
> > > > > > Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']

> > > > > > ---

**Comment by stormlrd** [comment]
further if I login on my test kitchen and do the following it works:
[vagrant@default-centos-72 ~]$ systemctl status cphalod.service
● cphalod.service - SYSV: CloudPassage Halo Agent
   Loaded: loaded (/etc/rc.d/init.d/cphalod)
   Active: failed (Result: exit-code) since Tue 2016-04-26 10:06:08 UTC; 8min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 23101 ExecStart=/etc/rc.d/init.d/cphalod start (code=exited, status=1/FAILURE)
[vagrant@default-centos-72 ~]$ /etc/rc.d/init.d/cphalod start
-bash: /etc/rc.d/init.d/cphalod: Permission denied
[vagrant@default-centos-72 ~]$ sudo /etc/rc.d/init.d/cphalod start
Please run /opt/cloudpassage/bin/configure                 [FAILED]
[vagrant@default-centos-72 ~]$ sudo /opt/cloudpassage/bin/configure --agent_key='abc123abc123abc123abc123abc123ab'
unknown switch '--agent_key=abc123abc123abc123abc123abc123ab'
Usage: /opt/bin/configure [--agent-key=<agent-key>] [--tag=<tag>] [--server-label=<server-label>] [--proxy=<proxy IP/FQDN:port>] [--proxy-user=<proxy user name>] [--proxy-password=<proxy password>] [--noproxy][--read-only=true/false] [--dns=true/false]
[vagrant@default-centos-72 ~]$ sudo /opt/cloudpassage/bin/configure --agent-key='abc123abc123abc123abc123abc123ab'
[vagrant@default-centos-72 ~]$ sudo /etc/rc.d/init.d/cphalod start
Starting the CloudPassage Halo Agent...                    [FAILED]
[vagrant@default-centos-72 ~]$ sudo /etc/rc.d/init.d/cphalod start
Starting the CloudPassage Halo Agent...                    [  OK  ]

note: that nothing was done between the last failure and ok. just waited 1 minute and re-ran the command.

**Comment by awilson-cloudpassage** [comment]
Hi Paul, thanks for reaching out.  I'm going to jump on this now.  Are you using the cookbook available through the Chef supermarket or are using the one directly from this github repo?  If you're using the one from this repo, what branch are you pulling from?

**Comment by awilson-cloudpassage** [comment]
Paul, in testing inside a CentOS 7.2 Docker container, I observe this after installation, before attempting to run /opt/cloudpassage/bin/configure:

```
[root@27c0cb749122 /]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
[root@27c0cb749122 /]# tree /opt/cloudpassage/
/opt/cloudpassage/
|-- LICENSE.txt
|-- bin
|   |-- configure
|   |-- cphalo
|   `-- cphalow
|-- data
|   `-- root_certs.pem
`-- log

```

And after running configure:

```
[root@27c0cb749122 /]# tree /opt/cloudpassage/
/opt/cloudpassage/
|-- LICENSE.txt
|-- bin
|   |-- configure
|   |-- cphalo
|   `-- cphalow
|-- data
|   |-- cphalo.properties
|   `-- root_certs.pem
`-- log
```

The .properties file contains configuration information until the agent is started, and this is the final state, after starting the agent:

```
/opt/cloudpassage/
|-- LICENSE.txt
|-- bin
|   |-- configure
|   |-- cphalo
|   `-- cphalow
|-- data
|   |-- id
|   |-- root_certs.pem
|   |-- store.db
|   `-- store.db.vector
`-- log
    `-- halo.log
```

Just installing the current version, 3.6.6-1, doesn't create the store.db file- that should only be created once /opt/cloudpassage/bin/configure is run successfully and the agent starts and registers to the grid.

There is a guard in the LWRP that forces systemd for RHEL-based OSes beyond version 7, because Chef wasn't accurately detecting the service manager when we were building and testing the cookbook.  (See https://github.com/cloudpassage/cloudpassage-chef-cookbook/blob/master/resources/agent.rb#L80)  If that's what's causing the issue, we may have a more interesting problem to engineer around.

I'm going to do some more testing in my environment today to see if I can reproduce the issue.  In the meantime, please let me know which version of the cookbook you're using, and what version of the agent you're installing.

Also worth mentioning... we're working on some modifications to the LWRP that will only restart the agent if the configuration is changed, instead of every time the recipe is run.  I want to make sure that this scenario doesn't persist for you after we've made that change.

-Ash

**Comment by stormlrd** [comment]
Chef supermarket as I am using a depends..

I'm using a test kitchen on a macbook pro using Vagrant not docker if that makes any difference.

In my metadata.rb I have the depends line.

in a attributes file I have the following:
default['cloudpassage']['agent_key'] = 'abc123abc123abc123abc123abc123ab'
default['cloudpassage']['tag'] = node['ec2']['stack_name']
default['cloudpassage']['label'] = node['hostname']
default['cloudpassage']['readonly'] = true
default['cloudpassage']['usedns'] = true
#defaults
default['cloudpassage']['grid_url'] = 'https://grid.cloudpassage.com/grid'
default['cloudpassage']['linux_agent_version'] = '3.6.6'

# If you define a proxy host, you must also define the port!

default['cloudpassage']['proxy_host'] = '10.0.2.2'
default['cloudpassage']['proxy_port'] = '8080'
default['cloudpassage']['proxy_user'] = nil
default['cloudpassage']['proxy_password'] = nil
default['cloudpassage']['read_only'] = false
default['cloudpassage']['server_tag'] = nil
default['cloudpassage']['server_label'] = nil
default['cloudpassage']['dns'] = true
default['cloudpassage']['yum_repo_url'] = 'http://packages.cloudpassage.com/redhat/$basearch'
default['cloudpassage']['apt_key_url'] = 'http://packages.cloudpassage.com/cloudpassage.packages.key'
default['cloudpassage']['yum_key_url'] = 'http://packages.cloudpassage.com/cloudpassage.packages.key'

please note: a proxy is involved...

I have tried both ways..  include 'cloudpassage'  and
cloudpassage_agent 'halo' do
  agent_key 'abc123abc123abc123abc123abc123ab'
  server_tag node['ec2']['stack_name']
  action :install
end

to run the install from the chef supermarket version..  both with an attributes file and both ways fail.

**Comment by stormlrd** [comment]
Ok. I really hate to be a pain in the behind here.  I removed all the default['cloudpasssage'] entries in my attributes file and used only:
cloudpassage_agent 'halo' do
  agent_key 'abc123abc123abc123abc123abc123ab'
  server_tag node['ec2']['stack_name']
  action :install
end

to call your chef supermarket recipe.

I did a kitchen destroy and a kitchen converge on centos.

And I received no errors on the server build.  However when I login the cphalo isn't in ps aux.  trying to start it using sudo /opt/cloudpassage/bin/cphalo hasn't helped either as it just sits there and hangs.

so I've added in just the below to the attributes:
default['cloudpassage']['proxy_host'] = '10.0.2.2'
default['cloudpassage']['proxy_port'] = '8080'
default['cloudpassage']['proxy_user'] = nil

and will try again.

**Comment by stormlrd** [comment]
And it bombed with just those.    Soooo possibly doesn't like proxy settings??

```
   Running handlers:
   [2016-04-26T20:34:09+00:00] ERROR: Running exception handlers
   Running handlers complete
   [2016-04-26T20:34:09+00:00] ERROR: Exception handlers complete
   Chef Client failed. 51 resources updated in 06 minutes 34 seconds
   [2016-04-26T20:34:09+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
   [2016-04-26T20:34:09+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
   [2016-04-26T20:34:09+00:00] ERROR: cloudpassage_agent[halo] (smtp::security line 3) had an error: Mixlib::ShellOut::ShellCommandFailed: service[CloudPassage Halo Agent for Linux] (/tmp/kitchen/cache/cookbooks/cloudpassage/resources/agent.rb line 77) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
   ---- Begin output of /bin/systemctl --system restart cphalod ----
   STDOUT: 
   STDERR: Job for cphalod.service failed because the control process exited with error code. See "systemctl status cphalod.service" and "journalctl -xe" for details.
   ---- End output of /bin/systemctl --system restart cphalod ----
   Ran /bin/systemctl --system restart cphalod returned 1
   [2016-04-26T20:34:11+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

> > > > > > Converge failed on instance <default-centos-72>.
> > > > > > Please see .kitchen/logs/default-centos-72.log for more details
> > > > > > ------Exception-------
> > > > > > Class: Kitchen::ActionFailed
> > > > > > Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']

> > > > > > ---

**Comment by awilson-cloudpassage** [comment]
The helper assembles the string to look like this: --proxy_host=10.0.0.22:8080  when it runs configure, and even if the address is incorrect the agent should start and the log file (located at /opt/cloudpassage/log/halo.log) will show this:
2016-04-26 21:38:22.7 d158f7444397[154] Information - Controller starting up ...
2016-04-26 21:38:22.8 d158f7444397[156] Information - Agent starting up ...
2016-04-26 21:38:22.8 d158f7444397[156] Information - Starting agent in read/write mode.
2016-04-26 21:39:22.9 d158f7444397[156] Error - Action alive failed. Poco exception 'Timeout: connect timed out: 10.0.0.22:8080'.
2016-04-26 21:40:23.0 d158f7444397[156] Error - Action alive failed. Poco exception 'Timeout: connect timed out: 10.0.0.22:8080'.

Can you tell me what's in the log file?  Does the store.db ever get created?  If the cphalo.properties file exists, can you redact the agent key and any other private information and paste the rest here?

**Comment by awilson-cloudpassage** [comment]
We can continue in this thread, or if you'd rather, we could have a phone call.
If you'd like to have a phone call, send your contact information to awilson@cloudpassage.com.

**Comment by stormlrd** [comment]
Happy to have it here in case someone else needs the history in the future.

> Can you tell me what's in the log file?

[vagrant@default-centos-72 ~]$ sudo cat /opt/cloudpassage/log/halo.log
2016-04-26 20:34:07.5 default-centos-72[23065] Information - Controller starting up ...
2016-04-26 20:34:07.5 default-centos-72[23067] Information - Agent starting up ...
2016-04-26 20:34:07.5 default-centos-72[23067] Information - Starting agent in read/write mode.
2016-04-26 20:34:08.6 default-centos-72[23067] Fatal - Authentication error with core!
2016-04-26 20:34:08.6 default-centos-72[23065] Information - child exited with status 78
2016-04-26 20:34:08.6 default-centos-72[23065] Information - child will not be restarted
2016-04-26 20:34:08.6 default-centos-72[23065] Information - Terminating

> Does the store.db ever get created?

Yes:
[vagrant@default-centos-72 ~]$ sudo ls /opt/cloudpassage/data
root_certs.pem  store.db

> If the cphalo.properties file exists, can you redact the agent key and any other private information and >paste the rest here?

cphalo.properties file does not exist.  sudo find / -name cphalo.properties returned nothing.

Is this because I'm testing with a fake Agent ID perhaps and am really just wasting your time? :)  I note that in my example above I've managed to get the agent manually to say "OK" when using the fake agent code.

e.g:
[vagrant@default-centos-72 ~]$ sudo /opt/cloudpassage/bin/configure --agent-key='abc123abc123abc123abc123abc123ab'
[vagrant@default-centos-72 ~]$ sudo /etc/rc.d/init.d/cphalod start
Starting the CloudPassage Halo Agent... [FAILED]
[vagrant@default-centos-72 ~]$ sudo /etc/rc.d/init.d/cphalod start
Starting the CloudPassage Halo Agent... [ OK ]

**Comment by awilson-cloudpassage** [comment]
Hahaha yep, there's your problem :)  The config vars will be written to the properties file, but if the proxy is unavailable for registration (rejection, in this case) the agent will remain alive for a while attempting to reach the grid.

**Comment by stormlrd** [comment]
Cool so just to be clear then :) For this noob nufty..

My problem was the fake Agent Code right.  The Proxy settings are working fine because it is able to reach the core for rejection-> rejecting Fatal - Authentication error with core!  eh.

Incoming - another stupid question.  Do you guys have a test agent code that verifies end to end on a test kitchen situation?  I guess I can remove the cloud passage for now and move onto other parts of my recipe in hope that when I get a valid agent code it'll be all ok when I release to UAT in AWS in future.

Thanks for your help.   

Really sorry to have wasted your time.

**Comment by awilson-cloudpassage** [comment]
Don't worry about it!  I should have asked that first, really.

  We don't have any agent activation codes for testing the cookbook.  Integration testing with the CloudPassage cookbook requires access to an active account.
  If you need a demo account, fill out the form here: https://www.cloudpassage.com/request-demo/ .  We would rather have you confident in the recipe you're building around our LWRP, and I'm interested in hearing about your use case.
