### ISSUE TITLE
Undefined method `actions'

### ISSUE THREAD

**Issue by 3phil4** [cloudpassage/cloudpassage-chef-cookbook#43]
**Getting the following error trying to run this cookbook:**

Recipe Compile Error in /var/chef/cache/cookbooks/cloudpassage/resources/agent.rb

NoMethodError

undefined method `actions' for #Class:0x0000000239ba78

Cookbook Trace:

  /var/chef/cache/cookbooks/cloudpassage/resources/agent.rb:1:in `class_from_file'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource/lwrp_base.rb:42:in`build_from_file'

Relevant File Content:

/var/chef/cache/cookbooks/cloudpassage/resources/agent.rb:

  1>> actions :install
  2:  default_action :install
  3:  property :agent_key, [String, nil]
  4:  property :grid_url, String, default: 'https://grid.cloudpassage.com/grid'
  5:  property :linux_agent_version, [String, nil]
  6:  property :proxy_host, [String, nil]
  7:  property :proxy_port, [String, nil]
  8:  property :proxy_user, [String, nil]
  9:  property :proxy_password, [String, nil]
 10:  property :read_only, kind_of: [TrueClass, FalseClass], default: false

**Running Chef Client, version 12.13.37 and Chef Server, Version 12.8.0. Node is Rhel 7.2**

**Comment by ashmastaflash** [comment]
Thanks @3phil4!  We'll have a look right away

**Comment by luckyinva** [comment]
Really looking forward to this update!

**Comment by ashmastaflash** [comment]
Hey @luckyinva, what version of Chef are you running?  The same as @3phil4?

**Comment by luckyinva** [comment]
@ashmastaflash yes we are in the same shop

**Comment by ashmastaflash** [comment]
Hi @luckyinva and @3phil4:
  We are having trouble reproducing this issue in our lab.  I want to get you into the official support channel so we can do a screen share and get to the bottom of this.  Please send an email to support@cloudpassage.com and mention that you're having trouble with Chef cookbook.  I'll be watching for your email in the support system, and we will get this fixed for you ASAP.

-Ash

**Comment by eatwithforks** [comment]
Closed Fixed.
