### ISSUE TITLE
apt on version 6.0 but pinned to 2.9

### ISSUE THREAD

**Issue by mhedgpeth** [cloudpassage/cloudpassage-chef-cookbook#70]
The apt cookbook is on version 6.0 but this cookbook is currently pinned to version 2.9. Is there a reason for this? Could you remove the pin or update it so the latest cookbook versions could be used?

**Comment by eatwithforks** [comment]
Hi Michael,

The latest version of apt we can pin would be 5.1.0 (2017-02-01). Versions 6.0.0+ has breaking changes that requires chef-client 12.9+. The cookbook needs to be backwards compatible with all supported chef-client versions. Would it work for you if the apt cookbook version is pinned to 5.1.0?

**Comment by eatwithforks** [comment]
Apt and Yum cookbooks are not required for v4.0.0 cloudpassage cookbook. Please use v4.0.0 for chef-client 12.9+.
