### ISSUE TITLE
Move S3 library and aws-sdk gem dependency out of cookbook scope

### ISSUE THREAD

**Issue by ncs-alane** [cloudpassage/cloudpassage-chef-cookbook#75]
Based on the changes made in the [4.0.1 release], the aws-sdk gem and S3 library are solely used for integration testing and as such should not exist in the scope of the cookbook. The current design places an unnecessary restriction on the interface of the cookbook which causes conflicts with other cookbooks that require a pinned version of the aws-sdk gem.

[4.0.1 release]: https://github.com/cloudpassage/cloudpassage-chef-cookbook/commit/b5a05b7d10b6ae862a1a944425a3811e16411f3e

**Comment by ashmastaflash** [comment]
Hey @ncs-alane sorry to keep you waiting.  Fixed cookbook heading to the supermarket soon...

**Comment by ncs-alane** [comment]
@ashmastaflash thank you kindly!
