### ISSUE TITLE
cannot install cloudpassage agent

### ISSUE THREAD

**Issue by VikasBains** [cloudpassage/cloudpassage-chef-cookbook#90]
connection to https://production.packages.cloudpassage.com/cloudpassage.packages.key
is intermittent. Is it known today{16 Jan 2019}?

```
ERROR:
Connection refused - Connection refused connecting to https://production.packages.cloudpassage.com/cloudpassage.packages.key
```

**Comment by ashmastaflash** [comment]
Hi @VikasBains thanks for reaching out. This issue should be resolved now.
Thanks for your patience, and feel free to reach out via support@cloudpassage.com if you experience this again, as response time via support email (for this particular type of issue) will be a little faster.
